version: '3'

networks:
  app-network:
    driver: bridge

services:

  nginx:
    image: nginx:stable-alpine
    container_name: ${DOCKER_APP_NAME:-project}-nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./storage/logs/nginx:/var/log/nginx/
    ports:
      - "${DOCKER_NGINX_PORT:-80}:80"
    depends_on:
      - app
    environment:
      TZ: ${DOCKER_WORKSPACE_TIMEZONE:-UTC}
    networks:
      - app-network

  app:
    image: app
    container_name: ${DOCKER_APP_NAME:-project}-app
    hostname: app-service
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/var/www:cached
    networks:
      - app-network

  mysql:
    image: mariadb
    container_name: ${DOCKER_APP_NAME:-project}-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DOCKER_MYSQL_PORT:-3306}:3306"
    volumes:
      - ${DOCKER_MYSQL_STORAGE:-./storage/database/mysql}:/var/lib/mysql/data:cached
    networks:
      - app-network
